### ISSUE TITLE
Update the Users GET request to fetch results from mongodb

### ISSUE THREAD

**Issue by zannis** [SocialHackersClass10/ChalleduApp#18] opened 2020-06-10 15:26 UTC
Integrate the GET users request with mongodb.

Acceptance criteria:
* GET /users should call find() from mongodb and return all results.
* If results exist, it should return statusCode 200 and a body in the following format:
`{
    users: [...array of user objects]
}`
* The returned user objects should only contain the following fields: 
    email
    full_name
    role
    affiliated_org
    image
Check out the 'delete' keyword in JS to remove the unnecessary fields
* In case of no results, it should also return statusCode 200 and a response with the same body format but an empty array

**Comment by student0b4dc0d3** [comment] 2020-06-11 18:12
A way to filter out the required fields on a mongodb fetch is as follows

SCHEMANAME.find({},'Code Name').sort({Name:1});

where the part 'Code Name' is the actual field name list

I hope this helps a little

**Comment by NickPapacostas** [comment] 2020-06-15 17:40
duplicate of https://github.com/SocialHackersClass10/ChalleduApp/issues/19

**Comment by zannis** [comment] 2020-06-16 10:26
Actually not a duplicate, this is about the GET all users endpoint. So there's still implementation work to be done here. :)

**Comment by Stef-Lev** [comment] 2020-06-18 16:32
Made the changes on ticket #30

**Closed** 2020-06-19 14:59 UTC
Labels: Back-End
